apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vm-staging

resources:
- ../../base

patches:
- path: vm-config.yaml
- path: datavolume-config.yaml
- path: container-config.yaml

namePrefix: staging-

labels:
- pairs:
    environment: staging
    version: v1.0.0

images:
- name: quay.io/techlead_allyson/hybrid-web-frontend
  newTag: latest
- name: quay.io/techlead_allyson/hybrid-api-backend
  newTag: latest
