apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-app
spec:
  template:
    spec:
      domain:
        cpu:
          cores: 3
        memory:
          guest: 6Gi
        resources:
          requests:
            memory: 6Gi
            cpu: 3
      volumes:
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |
            #cloud-config
            user: admin
            password: staging123
            chpasswd: { expire: False }
            ssh_pwauth: True
            package_update: true
            packages:
              - nginx
              - htop
            runcmd:
              - systemctl enable nginx
              - systemctl start nginx
              - echo "STAGING Environment - GitOps Managed VM - Version: 2.0" > /var/www/html/index.html
              - echo "Connected to VM Infrastructure" >> /var/www/html/index.html
              - firewall-cmd --permanent --add-service=http
              - firewall-cmd --reload
