# base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- vm-template.yaml

commonLabels:
  managed-by: argocd
  infrastructure: vm-platform

configurations:
- kustomizeconfig.yaml
