apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: dev1
  namespace: gitops
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: dev1
    spec:
      domain:
        cpu:
          cores: 4
        devices:
          disks:
            - disk:
                bus: virtio
              name: containerdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - name: vlan19-net
              bridge: {}
        resources:
          requests:
            memory: 20Gi
      networks:
        - name: vlan19-net
          multus:
            networkName: gitops/vlan19-bridge
      volumes:
        - name: containerdisk
          containerDisk:
            image: image-registry.openshift-image-registry.svc:5000/openshift-virtualization-os-images/rhel9-guest:latest
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              hostname: dev1
              ssh_pwauth: True
              users:
                - name: techlead
                  passwd: $6$XPkDQ4RzL0mv1BdM$hv4AWWrjPQ64DgxVGnkoct9K7P3BdaTVroXz7GcHRsIFEmypzQth6OATeOlR2MULHn80OJmd7ZTyb/HzXnJ3z/
              chpasswd:
                root:Adm123!
              packages:
                - httpd
                - firewalld
              runcmd:
                - systemctl enable httpd
                - systemctl start httpd
                - systemctl enable firewalld
                - systemctl start firewalld
                - firewall-cmd --permanent --add-service=http
                - firewall-cmd --permanent --add-service=ssh
                - firewall-cmd --reload
                - echo "<h1>Servidor HTTP Dev1</h1><p>Servidor funcionando corretamente!</p>" > /var/www/html/index.html
                - chown apache:apache /var/www/html/index.html
                - chmod 644 /var/www/html/index.html
              write_files:
                - path: /etc/httpd/conf.d/welcome.conf
                  content: |
                    <VirtualHost *:80>
                        DocumentRoot /var/www/html
                        ServerName dev1
                        ErrorLog /var/log/httpd/dev1_error.log
                        CustomLog /var/log/httpd/dev1_access.log combined
                    </VirtualHost>
                  permissions: '0644'

---
apiVersion: v1
kind: Service
metadata:
  name: dev1-http
  namespace: gitops
spec:
  selector:
    kubevirt.io/domain: dev1
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: dev1-http
  namespace: gitops
spec:
  to:
    kind: Service
    name: dev1-http
  port:
    targetPort: http

