apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: reboot-vm-role
  namespace: gitops
rules:
  - apiGroups: ["kubevirt.io"]
    resources: ["virtualmachines"]
    verbs: ["get", "patch"]

