apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitops         # obrigatório minúsculo
resources:
  - ../../base

patchesStrategicMerge:
  - vm-config.yaml
  - datavolume-config.yaml
  - container-config.yaml

labels:
  - pairs:
      environment: dev
      version: v1.0.0

images:
  - name: quay.io/techlead_allyson/hybrid-web-frontend
    newTag: latest
  - name: quay.io/techlead_allyson/hybrid-api-backend
    newTag: latest

