apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: gitops
spec:
  template:
    spec:
      domain:
        cpu:
          cores: 2
        memory:
          guest: 4Gi
      volumes:
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |
            #cloud-config
            user: admin
            password: admin123
            chpasswd: { expire: False }
            ssh_pwauth: True
            package_update: true
            packages:
              - nginx
            runcmd:
              - systemctl enable nginx
              - systemctl start nginx
              - echo "DEV Environment - GitOps Managed VM" > /var/www/html/index.html
              - firewall-cmd --permanent --add-service=http
              - firewall-cmd --reload
