apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- web-frontend.yaml
- api-backend.yaml

labels:
- pairs:
    managed-by: argocd
    infrastructure: vm-platform
    component: containers

images:
- name: quay.io/techlead_allyson/hybrid-web-frontend
  newTag: latest
- name: quay.io/techlead_allyson/hybrid-api-backend
  newTag: latest
