apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: rhel9-vm
  namespace: gitops
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: rhel9-vm
    spec:
      domain:
        cpu:
          cores: 2
        devices:
          disks:
            - disk:
                bus: virtio
              name: containerdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
        resources:
          requests:
            memory: 4Gi
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/rockylinux/rockylinux:9
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              hostname: rhel9-vm
              ssh_pwauth: True
              users:
                - name: cloud-user
                  ssh-authorized-keys:
                  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDRi8B4JJh5A81arjChKWm4VhyKmVky8rqN/0iiJvQS02jujg7DdlyHcSbadEoU+hm9euf14tF0XIBaj58JzURvdK8cngfpwP+ENxp9IUBJNuFAGD3OdXH3XZIrY/YM6fJ/3TNPIJuZryt9CPmtnyDYGIkotSJM8evdS+RfCZG3218DnLdJRKCbByrr1ULNzMLvVXFA6d+RiyClnrDV88690d2OZnLt/S3baiMuReFG0cFUlcGXFNawFrkAGMoLIfIW7AYjLIQOheKInz/nox2ErqOwMCZ4leemSi3bjTVzEItZKrGezoSRevyTEn9zmkxECIYYcfEzBdcUHb767OWj allyson.brito@MacBook-Pro-de-Allyson.local

